### PR TITLE
update og card

### PR DESCRIPTION
**Pull request by ThaFridge**
added new og facebook card 1200x623
added new twitter only og card 400x400

### CODE REVIEW

**Comment by rynomster** [comment]
Should index.html not also reflect this?

**Comment by rynomster** [comment]
```
        <meta name="twitter:card" content="summary">
        <meta name="twitter:image" content="https://blocktix.io/img/og-image.png">
        <meta name="twitter:site" content="@blocktix">
        <meta name="twitter:title" content="Blocktix">
        <meta name="twitter:description" content="A chain of custody ticketing system">
```

**Comment by ThaFridge** [comment]
Nope, twitter uses a different style of OG cards, they have 3 sizes while facebook/reddit/etc users the universal. with this update im hitting midsize version

**Comment by ThaFridge** [comment]
updated with the correct index.html

**Pull request merged**
