### PR TITLE
 UI fixes + animations + small changes + iOS fixes

### PR DESCRIPTION
**Pull request by temkin**

### CODE REVIEW

**Comment by rynomster** [comment]
screenshot from 2017-11-13 16-12-00

The little animation seems to be very small compared to the other images

**Comment by temkin** [comment]
hmmm, maybe browser cache? 
should be displayed like http://joxi.ru/Dr81oejukYvajm 

Could you say: what screen resolution used?

**Comment by rynomster** [comment]
I'm using 4k.. I can't zoom out like normal websites.. however if I do zoom out, only that image gets smaller, the rest stay the same size

**Comment by temkin** [comment]
ok, I try to optimize this animation for 4k screens

**Comment by rynomster** [comment]
The animations are looking great! The responsiveness of the team section is completely broken now however.

**Comment by temkin** [comment]
What browser do you use?

**Comment by rynomster** [comment]
I use google chrome

**Comment by rynomster** [comment]
Still getting the problem on UHD.

You can replicate it by setting the scale factor on Chrome lower
This is how you do it on ubuntu:
`google-chrome-stable --force-device-scale-factor=0.5`

I just tested this a FHD screen.

**Comment by rynomster** [comment]
Sorry that's my bad.. the scale factor doesn't seem to work lower than 1. I didn't realise this screen was 1440p

**Comment by temkin** [comment]
I can't reproduce this on Mac:
```console
$  ./Google\ Chrome --force-device-scale-factor=0.5
[22360:47107:1122/091556.570903:ERROR:browser_gpu_channel_host_factory.cc(108)] Failed to launch GPU process.
```

My screen resolution is 2880 x 1800 (MBP) I try to scale down by 80% and still works. On this week new monitor should be delivered and I'll test again.

**Comment by rynomster** [comment]
Try to make the width around 25% of the screen, and the height 100%, with
the scale factor set low. That's when the issue occurs, when there should
only be 2 team members on the screen, it makes a scroll bar instead of the
radio buttons, or it'll make a radio button but still needs to scroll a bit.

**Pull request merged**
